name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Hello world       # Name of step
      uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
      with:                                            # This section is needed if you need to pass arguments to the action
        who-to-greet: 'Mona the Octocat'
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
    - uses: actions/setup-node@v1
      with:
        dotnet-version: '3.1.405' # SDK Version to use; x will use the latest version of the 3.1 channel
        node-version: '11.13.0'
    - run: dotnet build
    - run: dotnet test
    - run: cd DotnetTemplate.Web && npm i && npm t && npm run lint